### ISSUE TITLE
tab not loaded when opening a new session

### ISSUE THREAD

**Issue by lazymonkey2** [mahdi-mallaee/flow#13]
Hi, 
I saved a session and have an issue when reopening it:  the tab in foreground is not loaded (the page is empty).
To view the page contents I have to switch to a different tab and then go back to the original tab.
I like that the tabs are loaded only when clicked, but the "default" tab should be loaded automatically.

I seems that instead of the foreground tab it is loaded the last tab on the right.

**Comment by mahdi-mallaee** [comment]
Hi,
I discard the tabs when opening a session to improve load time and resource usage and just load the last tab, I assumed that is always the case when opening a session.
Can you explain how another tab is highlighted (is foreground tab as you say) when opening a session?

**Comment by lazymonkey2** [comment]
sorry I think this issue was because of another extension to manage tabs position.
I uninstalled it and it seems that it's working correctly now.

BTW I have other suggestions but I'll create new bug reports.
thanks.
