### ISSUE TITLE
close the popup menu after selectin a session

### ISSUE THREAD

**Issue by lazymonkey2** [mahdi-mallaee/flow#20]
after selecting a session a new page is opened, but in the original window the popup menu is still opened.
each time I return to the original window I have to close it.
please can you close the popup menu automatically after I have selected a session?

**Comment by mahdi-mallaee** [comment]
#[commit](https://github.com/mahdi-mallaee/flow/commit/6fe889fb602cfab3b0a2dc9716d4325424afc120)
Thanks for the feedback.
Just added this and it will be in the next version.
